# Generated by Django 3.1 on 2020-08-30 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name must be a maximum of 100 characters', max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name must be a maximum of 150 characters', max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('decription', models.TextField(help_text='Name must be a maximum of 4000 characters', max_length=4000)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('brochure', models.FileField(blank=True, max_length=150, null=True, upload_to='static/documents/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField()),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='properties.property')),
            ],
            options={
                'ordering': ['capacity'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name must be a maximum of 50 characters', max_length=50, unique=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.room_type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=30)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Property_Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='properties.facility')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='properties.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='facilities',
            field=models.ManyToManyField(through='properties.Property_Facility', to='properties.Facility'),
        ),
    ]
