# Generated by Django 3.1 on 2020-09-23 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title must be max 100 characters', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image1', models.ImageField(max_length=254, upload_to='images/')),
                ('content', models.TextField(help_text='Content must be a maximum of 5000 characters', max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
