# Generated by Django 3.1 on 2020-09-23 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
