# Generated by Django 3.1 on 2020-09-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20200830_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='available', max_length=20),
            preserve_default=False,
        ),
    ]
