# Generated by Django 3.1 on 2020-09-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_room_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Apartment',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='room',
            new_name='apartment',
        ),
    ]
