# Generated by Django 3.1 on 2020-09-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200911_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='first_payment',
            field=models.CharField(choices=[('Paid', 'Paid'), ('No Payment', 'No Payment')], default='No Payment', max_length=15),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration_type',
            field=models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], max_length=7),
        ),
    ]
