# Generated by Django 3.1 on 2020-09-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200911_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='made_payment',
            field=models.BooleanField(default=False),
        ),
    ]
