# Generated by Django 3.1 on 2020-09-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20200912_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
